name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Publish binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          artifact_name: service/CheckMeet.dmg
          asset_name: CheckMeet-Mac-$tag.dmg
        - os: windows-latest
          artifact_name: service/dist/CheckMeet.exe
          asset_name: CheckMeet-Windows-$tag.exe

    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Import codesign key
      if: ${{ matrix.os == 'macos-latest' }}
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
    - name: Install dependencies
      working-directory: ${{github.workspace}}/service
      run: |
        python -m pip install pipenv
        pipenv install --skip-lock
    - name: Build package
      if: ${{ matrix.os == 'macos-latest' }}
      working-directory: ${{github.workspace}}/service
      run: pipenv run ./build_dmg.sh
    - name: Build package
      if: ${{ matrix.os != 'macos-latest' }}
      working-directory: ${{github.workspace}}/service
      run: |
        pipenv run pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
        pipenv run pyinstaller --clean --onefile --name CheckMeet --windowed launch_service.py
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true
