name: Pack Service

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    name: Build packages
    runs-on: macos-10.15
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Import codesign key
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
    - name: Install dependencies
      working-directory: ${{github.workspace}}/service
      run: |
        python -m pip install pipenv
        pipenv install --skip-lock
    - name: Build package
      working-directory: ${{github.workspace}}/service
      run: pipenv run ./build_dmg.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: service/CheckMeet.dmg
