name: Pack Service

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Import codesign key
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
    - name: Install dependencies
      working-directory: ${{github.workspace}}/service
      run: |
        python -m pip install pipenv
        pipenv install --skip-lock
    - name: Build package
      working-directory: ${{github.workspace}}/service
      run: pipenv run ./build_dmg.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: service/CheckMeet.dmg
        asset_name: CheckMeet-Mac-$tag.dmg
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true
